% -------------------------------------------------------------------
%  Generated by MATLAB on 16-Jul-2018 15:33:50
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('chunck.mat');

z = saveVarsMat.z; % <2985x2 double> too many elements

clear saveVarsMat;
